// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Qué cliente es, que solo decide cómo se lanza.
 */
export type ClientKind = "autofirma" | "rfirma";
