// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Store } from "./Store";

/**
 * El perfil aislado de un almacén: el envoltorio que lanza al cliente contra él y la raíz con la
 * que sirve el canal.
 */
export type Profile = { store: Store, launcher: string, trust_root: string, };
