// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteService } from "./RemoteService";
import type { RequestHeaders } from "./RequestHeaders";

/**
 * Una petición: lo que un servidor falso de la sede recibió del cliente, sin valores.
 */
export type ReceivedRequest = { service: RemoteService, method: string, path: string, query: Array<string>, body: Array<string>, content_type: string | null, headers: RequestHeaders, };
