// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";
import type { Header } from "./Header";
import type { OrphanView } from "./OrphanView";
import type { SetView } from "./SetView";
import type { Summary } from "./Summary";

export type ReportView = { client: string, kind: ClientKind, header: Header, summary: Summary, sets: Array<SetView>, orphans: Array<OrphanView>, };
