// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Si las peticiones de los dos trámites coinciden como multiconjunto, dé cada uno lo que dé.
 */
export type RequestsComparison = "match" | "differ" | "not_comparable";
