// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Tranches } from "./Tranches";

/**
 * Lo que se pide correr: una comprobación, un conjunto entero o sus pendientes, o lo pendiente de
 * unos tramos.
 */
export type Request = { check: string, } | { set: string, pending?: boolean, } | { tranches: Tranches, };
