// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckView } from "./CheckView";
import type { Summary } from "./Summary";

export type SetView = { name: string, summary: Summary, checks: Array<CheckView>, };
