// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";

export type Side = { client: string, kind: ClientKind, client_version: string, };
