// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * El almacén de un perfil aislado: `rsa` y `ec`, una NSS sin contraseña con un solo certificado;
 * `token`, SoftHSM con PIN; `token_apart`, el token sin registrar junto a una NSS con otro; `ed25519`,
 * un token sin registrar con una sola clave Ed25519; `several` y `expired`, NSS con varios, para los
 * filtros.
 */
export type Store = "rsa" | "ec" | "token" | "token_apart" | "ed25519" | "several" | "expired";
