// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Summary = { total: number, compliant: number, noncompliant: number, 
/**
 * Los NO CONFORME con alguna etiqueta, sea del cliente que sea.
 */
explained: number, not_observable: number, pending: number, };
