// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Los tramos de una tanda de pendientes: solo sin persona, el resto, o todos.
 */
export type Tranches = "unattended" | "attended" | "all";
