//! Lo que `/design-sync` compila para Claude Design, generado por `just design-sync-selection` desde los títulos de las historias (ADR-0046).

import "./src/design-system/index.css";
import "./src/app.css";

export { Badge } from "./src/design-system/Badge";
export { Button } from "./src/design-system/Button";
export { Card } from "./src/design-system/Card";
export { DesignRoot } from "./src/design-system/DesignRoot";
export { Dialog } from "./src/design-system/Dialog";
export { Field } from "./src/design-system/Field";
export * from "./src/design-system/icons";
export { Menu, MenuItem } from "./src/design-system/Menu";
export { Popover } from "./src/design-system/Popover";
export { ProgressBar } from "./src/design-system/ProgressBar";
export { Row } from "./src/design-system/Row";
export { Select } from "./src/design-system/Select";
export { Stack } from "./src/design-system/Stack";
export { Switch } from "./src/design-system/Switch";
export { DocumentTabs } from "./src/documents/DocumentTabs";
export { RecentRows, RecentsSection } from "./src/documents/RecentRows";
export { ErrorNotice } from "./src/errors/ErrorNotice";
export { PlacementBlock } from "./src/placement/PlacementBlock";
export { SedeConsent } from "./src/sede/SedeConsent";
export { SedeOutcome } from "./src/sede/SedeOutcome";
export { SedeView } from "./src/sede/SedeView";
export { Header } from "./src/shell/Header";
export { MainWindow } from "./src/shell/MainWindow";
export { CertificateCard } from "./src/signing/CertificateCard";
export { CertificateSelect } from "./src/signing/CertificateSelect";
export { SignAnywayDialog } from "./src/signing/SignAnywayDialog";
export { SignaturesDialog } from "./src/signing/SignaturesDialog";
export { SignaturesPanel } from "./src/signing/SignaturesPanel";
export { SigningPanel } from "./src/signing/SigningPanel";
export { SigningProgressDialog } from "./src/signing/SigningProgressDialog";
export { UnsealedPagesDialog } from "./src/signing/UnsealedPagesDialog";
export { VisibleSignatureFieldset } from "./src/signing/VisibleSignatureFieldset";
export { StatusView } from "./src/status/StatusView";
export { WithdrawCertificateView } from "./src/status/WithdrawCertificateView";
export { NewVersionStrip } from "./src/updates/NewVersionStrip";
export { DocumentViewer } from "./src/viewer/DocumentViewer";
