// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Qué necesita una comprobación de la persona que está delante, en el orden de sus tramos.
 */
export type Assistance = "none" | "click" | "person";
