// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultName } from "./ResultName";

export type CheckView = { id: string, chapter: string, statement: string, citation: string, warning: string | null, question: string | null, state: ResultName, observation: string | null, date: string | null, duration_ms: number | null, };
