// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Assistance } from "./Assistance";
import type { KnownBug } from "./KnownBug";
import type { ResultName } from "./ResultName";
import type { Store } from "./Store";

export type CheckView = { id: string, chapter: string, statement: string, citation: string, warning: string | null, assistance: Assistance | null, store: Store, bug: KnownBug | null, deprecated: boolean, state: ResultName, observation: string | null, date: string | null, duration_ms: number | null, };
