// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";
import type { Profile } from "./Profile";

export type Client = { kind: ClientKind, binary: string, profiles: Array<Profile>, };
