// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClientChoice = { kind: string, binary: string | null, trust_root: string | null, };
