// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";

export type Client = { kind: ClientKind, binary: string, launcher: string, trust_root: string, store: string, };
