// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Row } from "./Row";
import type { Side } from "./Side";

export type Comparison = { a: Side, b: Side, rows: Array<Row>, differing: number, };
