// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Las coordenadas que se deducen solas al crear un informe; la versión del cliente, no.
 */
export type DeducedCoordinates = { os: string, os_version: string, transport: string, };
