// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultName } from "./ResultName";

/**
 * Una comprobación medible que no da lo previsto: un fallo de la suite o de la referencia.
 */
export type Discrepancy = { id: string, expected: ResultName, observed: ResultName, cause: string | null, note: string | null, };
