// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Las coordenadas de un informe, tomadas una sola vez al crearlo.
 */
export type Header = { os: string, os_version: string, client_version: string, transport: string, store: string, date: string, };
