// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Si el bug sigue vivo en la rama de desarrollo del original.
 */
export type InMaster = "fixed" | "present" | "partial";
