// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InMaster } from "./InMaster";

/**
 * Una ficha `BUG-NN` del anexo A1: su título, sin marcas de Markdown, y su estado en `master`.
 */
export type KnownBug = { id: string, title: string, master: InMaster, };
