// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Una línea del registro en vivo y la comprobación que la dio.
 */
export type LiveLine = { check: string | null, line: string, };
