// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Las coordenadas con las que se crea un informe, tal y como llegan de la página.
 */
export type NewReport = { name: string, client_version: string, os: string, os_version: string, transport: string, };
