// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResultName } from "./ResultName";

export type OrphanView = { id: string, state: ResultName, };
