// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QuestionView = { check: string, prompt: string, kind: "outcome" | "briefing", };
