// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * El servicio remoto de la sede que recibe una petición del cliente.
 */
export type RemoteService = "presigner" | "postsigner";
