// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientKind } from "./ClientKind";

/**
 * Un informe del directorio de informes, tal y como se ofrece para elegirlo o compararlo.
 */
export type ReportEntry = { name: string, kind: ClientKind | null, client: string | null, client_version: string | null, date: string | null, complaint: string | null, };
