// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RemoteService } from "./RemoteService";

/**
 * Lo que difiere de un servicio remoto entre las peticiones de los dos lados, ya explicado.
 */
export type RequestDifference = { service: RemoteService, differences: Array<string>, };
