// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AllPending } from "./AllPending";

/**
 * Lo que se pide correr: una comprobación, un conjunto entero o sus pendientes, o todo lo pendiente.
 */
export type Request = { check: string, } | { set: string, pending?: boolean, } | AllPending;
