// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Las cabeceras de una petición que cuentan, normalizadas: `Origin` sin puerto y de
 * `Authorization` solo el esquema.
 */
export type RequestHeaders = { origin: string | null, authorization: string | null, accept: string | null, };
