// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Los cuatro nombres en pantalla de un resultado, tal y como viajan a la consola.
 */
export type ResultName = "CONFORME" | "NO CONFORME" | "NO OBSERVABLE" | "PENDIENTE";
