// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReceivedRequest } from "./ReceivedRequest";
import type { RequestsComparison } from "./RequestsComparison";
import type { ResultName } from "./ResultName";

export type Row = { id: string, set: string, chapter: string, citation: string, a: ResultName, b: ResultName, differ: boolean, requests: RequestsComparison, a_requests: Array<ReceivedRequest> | null, b_requests: Array<ReceivedRequest> | null, };
