// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CallView } from "./CallView";
import type { Client } from "./Client";
import type { ReportEntry } from "./ReportEntry";
import type { ReportView } from "./ReportView";
import type { RunningView } from "./RunningView";

export type Snapshot = { client: Client | null, client_complaints: Array<string>, resolving_client: boolean, report_name: string | null, report: ReportView | null, reports: Array<ReportEntry>, running: RunningView | null, queued: Array<string>, call: CallView | null, why_pending: { [key in string]: string }, };
