// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * El almacén de un perfil aislado: `rsa` y `ec`, una NSS sin contraseña con un solo certificado;
 * `token`, SoftHSM con PIN; `several` y `expired`, NSS con varios, para los filtros.
 */
export type Store = "rsa" | "ec" | "token" | "several" | "expired";
