// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * El almacén de un perfil aislado: `rsa` y `ec`, una NSS sin contraseña con un solo certificado;
 * `token`, SoftHSM con PIN; `token_apart`, el token sin registrar junto a una NSS con otro; `several`
 * y `expired`, NSS con varios, para los filtros.
 */
export type Store = "rsa" | "ec" | "token" | "token_apart" | "several" | "expired";
