// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Un fallo de la suite en una comprobación, que la página avisa aparte de su resultado.
 */
export type SuiteFailure = { check: string, why: string, };
