// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Summary = { total: number, compliant: number, 
/**
 * Sin los de un formato deprecado, que no son un fallo del cliente y van en `deprecated`.
 */
noncompliant: number, deprecated: number, not_observable: number, pending: number, };
