// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Discrepancy } from "./Discrepancy";

export type Validation = { "result": "validated" } | { "result": "discrepant", discrepancies: Array<Discrepancy>, };
